zookeeper:
  image: enow/zookeeper
  ports:
    - "2181:2181"
nimbus:
  image: enow/storm-nimbus
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
    - "22"
  links:
    - zookeeper:zk
supervisor:
  image: enow/storm-supervisor
  ports:
    - "8000:8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: enow/storm-ui
  ports:
    - "8080:8080"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
