nimbus:
  command: --daemon nimbus drpc
  image: enow/storm-dev
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
  external_links:
    - storm_zookeeper_1:zk
supervisor:
  command: --daemon supervisor logviewer
  image: enow/storm-dev
  ports:
    - "8000:8000"
    - "6700:6700"
    - "6701:6701"
    - "6702:6702"
    - "6703:6703"
  links:
    - nimbus:nimbus
  external_links:
    - storm_zookeeper_1:zk
ui:
  command: --daemon ui
  image: enow/storm-dev
  ports:
    - "8080:8080"
  links:
    - nimbus:nimbus
  external_links:
    - storm_zookeeper_1:zk
